### ISSUE TITLE
Java Client and clobber update [JIRA: CLIENTS-177]

### ISSUE THREAD

**Issue by cosmink** [basho/riak-java-client#493]
I’m doing a fairly “by the book” clobber update (store and fetch below work fine) on an entity using the Java client. I’m seeing an error that happens at type-inference time within the Riak Java client. I’m pasting below the exact test that I’m using to generate this, as well as the stacktrace.

```
@Test
public void testRiakUpdate() throws Exception {
    RiakNode node = new RiakNode.Builder().withRemoteAddress("192.168.168.2").withRemotePort(8087).build();
    RiakCluster cluster = new RiakCluster.Builder(node).build();
    cluster.start();
    RiakClient client = new RiakClient(cluster);

    SomeEntity entity = new SomeEntity();
    entity.setName("John Doe");
    entity.setDescription("Some Description");
    Location location = new Location(new Namespace("bucket"), "entity-key");

    // Store
    StoreValue storeOp = new StoreValue.Builder(entity).withLocation(location).build();
    client.execute(storeOp);

    // Fetch
    FetchValue fetchOp = new FetchValue.Builder(location).build();
    entity = client.execute(fetchOp).getValue(SomeEntity.class);

    // Update
    entity.setName("New name");
    UpdateValue updateOp = new UpdateValue.Builder(location)
            .withFetchOption(FetchValue.Option.DELETED_VCLOCK, true)
            .withUpdate(UpdateValue.Update.clobberUpdate(entity))
            .build();
    client.execute(updateOp).getValue(SomeEntity.class);
}

private static class SomeEntity {
    private String name;
    private String description;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
```

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.basho.riak.client.api.commands.kv.UpdateValue$1.handle(UpdateValue.java:149) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.api.commands.ListenableFuture.notifyListeners(ListenableFuture.java:78) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.api.commands.CoreFutureAdapter.handle(CoreFutureAdapter.java:120) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.FutureOperation.fireListeners(FutureOperation.java:131) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.FutureOperation.setResponse(FutureOperation.java:170) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.RiakNode.onSuccess(RiakNode.java:823) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:58) ~[riak-client-2.0.0.jar:na]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
20:34:13.390 [nioEventLoopGroup-2-1] DEBUG c.b.riak.client.core.FutureOperation - IllegalStateException; required: [CREATED, WRITTEN, RETRY] current: COMPLETE  
20:34:13.391 [nioEventLoopGroup-2-1] WARN  i.n.channel.DefaultChannelPipeline - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.basho.riak.client.api.commands.kv.UpdateValue$1.handle(UpdateValue.java:149) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.api.commands.ListenableFuture.notifyListeners(ListenableFuture.java:78) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.api.commands.CoreFutureAdapter.handle(CoreFutureAdapter.java:120) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.FutureOperation.fireListeners(FutureOperation.java:131) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.FutureOperation.setResponse(FutureOperation.java:170) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.RiakNode.onSuccess(RiakNode.java:823) ~[riak-client-2.0.0.jar:na]
	at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:58) ~[riak-client-2.0.0.jar:na]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [netty-all-4.0.17.Final.jar:4.0.17.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

**Comment by binarytemple** [comment]
I reproduced the crash using Cosminks code, as a work around I also got it to work with the following:

```
import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.api.commands.kv.FetchValue;
import com.basho.riak.client.api.commands.kv.StoreValue;
import com.basho.riak.client.api.commands.kv.UpdateValue;
import com.basho.riak.client.api.convert.ConverterFactory;
import com.basho.riak.client.api.convert.JSONConverter;
import com.basho.riak.client.core.RiakCluster;
import com.basho.riak.client.core.RiakNode;
import com.basho.riak.client.core.query.Location;
import com.basho.riak.client.core.query.Namespace;
import com.fasterxml.jackson.core.type.TypeReference;
import junit.framework.TestCase;
import org.junit.Test;

public class FooTest extends TestCase{

    public static class SomeEntity {
        private String name;
        private String description;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
    }


    @Test
    public void testRiakUpdate() throws Exception {


        ConverterFactory.getInstance().registerConverterForClass(
                SomeEntity.class, new JSONConverter<>(new TypeReference<SomeEntity>(){})
        );

        RiakNode node = new RiakNode.Builder().withRemoteAddress("localhost").withRemotePort(10017).build();

        RiakCluster cluster = new RiakCluster.Builder(node).build();
        cluster.start();
        RiakClient client = new RiakClient(cluster);

        SomeEntity entity = new SomeEntity();
        entity.setName("John Doe");
        entity.setDescription("Some Description");
        Location location = new Location(new Namespace("default","bucket"), "entity-key");

        // Store
        StoreValue storeOp = new StoreValue.Builder(entity).withLocation(location).build();
        client.execute(storeOp);

        // Fetch
        FetchValue fetchOp = new FetchValue.Builder(location).build();
        FetchValue.Response response = client.execute(fetchOp);


         entity = response.getValue(SomeEntity.class);
        System.err.println("entity:" + entity);
        // Update
        entity.setName("New name");
        final SomeEntity finalEntity = entity;
        UpdateValue updateOp = new UpdateValue.Builder(location)
                .withFetchOption(FetchValue.Option.DELETED_VCLOCK, true)
                .withUpdate(UpdateValue.Update.clobberUpdate(entity))
                .withUpdate(new UpdateValue.Update<SomeEntity>() {
                    @Override
                    public SomeEntity apply(SomeEntity original) {
                        return finalEntity;
                    }
                })
                .build();
        client.execute(updateOp).getValue(SomeEntity.class);
    }


}
```

I then confirmed it had stored correctly using curl:

```
[/basho/riak%]curl "localhost:10018/types/default/buckets/bucket/keys/entity-key"
{"name":"New name","description":"Some Description"}%
```

Worth noting that I'm using the following client, compiled and Maven installed locally:
```
 <dependency>
            <groupId>com.basho.riak</groupId>
            <artifactId>riak-client</artifactId>
            <version>2.0.1-SNAPSHOT</version>
        </dependency>
```

And version 2.0.4 of Riak itself.

**Comment by broach** [comment]
@binarytemple Yeah, sorry - should have commented - @cosmink and I discussed this in email. It's a Greek tragedy involving type erasure. I have to see if I can hack (moar) around it. Simply extending `UpdateValue.Update` yourself is the easy fix, as you found out.

**Comment by broach** [comment]
Importing to JIRA (hopefully)

**Comment by broach** [comment]
Import to JURA

**Comment by broach** [comment]
So yeah ... about that. 

Basically, I fixed the glitch. As in I removed the static factory methods. In trying to be all slick with generics and inferring the type... type erasure came back to bite me. You simply have to extend the `Update<T>` class yourself with something that explicitly defines the type as otherwise the type gets erased entirely, and there's no way to hack around it.

**Comment by cosmink** [comment]
Thanks Brian! Yeah, I think at least this way it's explicit what needs to happen. I feel your pain about generics!

**Comment by broach** [comment]
@cosmink It was entirely due to me trying to be too smart for my own good. "Hey, this way, the `UpdateValue` class doesn't have to be a generic ... I'll just infer the types from places using reflection!" ... because right, that never ends in tears ...
