### ISSUE TITLE
Java Client 1.4.4 - AcquireConnectionTimeoutException breaking connection pool [JIRA: CLIENTS-562]

### ISSUE THREAD

**Issue by submitteddenied** [basho/riak-java-client#542]
Hi all,

I am running and App with riak-client 1.4.4 and after approximately a week of running, the RiakConnectionPool appears to lose its ability to create new connections to the Riak cluster. In all cases, restarting the java process resolves the issue.

I poked around in the code a bit, but I can't see anything in the Riak Client that would be causing this, unless there were some socket connections that didn't get garbage collected and are preventing new connections from being made. Is there something on the Riak Server side that might be causing this?

Client:
riak-client:1.4.4

Server:
riak.x86_64:2.1.1-1

Stack trace:

```
ERROR [2015-08-28 17:04:18,313] com.riotgames.highlander.resources.tournament.TournamentDAO: Riak exception thrown:
! com.basho.riak.client.RiakRetryFailedException: com.basho.riak.pbc.AcquireConnectionTimeoutException: timeout from 
socket connection connect timed out
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:79) ~[my_api.jar:na]
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:81) ~[my_api.jar:na]
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:81) ~[my_api.jar:na]
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:81) ~[my_api.jar:na]
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:53) ~[my_api.jar:na]
! at com.basho.riak.client.bucket.FetchBucket.execute(FetchBucket.java:72) ~[my_api.jar:na]
! at com.riotgames.my_api.riak.RiakObjectStore.getKeysByIndex(RiakObjectStore.java:78) ~[my_api.jar:na]
<-- snip app stuff -->
Caused by: ! com.basho.riak.pbc.AcquireConnectionTimeoutException: timeout from socket connection connect timed out
! at com.basho.riak.pbc.RiakConnectionPool.getConnection(RiakConnectionPool.java:391) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnectionPool.doGetConection(RiakConnectionPool.java:336) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnectionPool.access$400(RiakConnectionPool.java:45) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnectionPool$State$2.getConnection(RiakConnectionPool.java:75) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnectionPool.getConnection(RiakConnectionPool.java:332) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakClient.getConnection(RiakClient.java:105) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakClient.getBucketProperties(RiakClient.java:792) ~[my_api.jar:na]
! at com.basho.riak.client.raw.pbc.PBClientAdapter.fetchBucket(PBClientAdapter.java:267) ~[my_api.jar:na]
! at com.basho.riak.client.bucket.FetchBucket$1.call(FetchBucket.java:74) ~[my_api.jar:na]
! at com.basho.riak.client.bucket.FetchBucket$1.call(FetchBucket.java:72) ~[my_api.jar:na]
! at com.basho.riak.client.cap.DefaultRetrier.attempt(DefaultRetrier.java:72) ~[my_api.jar:na]
!... 59 common frames omitted
Caused by: ! java.net.SocketTimeoutException: connect timed out
! at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_31]
! at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_31]
! at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_31]
! at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_31]
! at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_31]
! at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_31]
! at com.basho.riak.pbc.RiakConnection.<init>(RiakConnection.java:68) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnection.<init>(RiakConnection.java:51) ~[my_api.jar:na]
! at com.basho.riak.pbc.RiakConnectionPool.getConnection(RiakConnectionPool.java:388) ~[my_api.jar:na]
!... 69 common frames omitted
```

**Comment by alexmoore** [comment]
Hi @submitteddenied,

Did you ever find an answer to your issue?  The 1.4.4 Client isn't supported anymore, have you looked into the 2.0 client?

Thanks,
Alex

**Comment by alexmoore** [comment]
Hi,

Java Client 1.4.4 is no longer supported. Riak Java clients 2.0 and later are compatible with Riak 1.4.X versions, however, so that may be an option for you.

Closing this issue.
