### ISSUE TITLE
Getting a conversion error when I try to store a protobuf object in Riak [JIRA: CLIENTS-693]

### ISSUE THREAD

**Issue by vchan-acm** [basho/riak-java-client#586]
Riak Java Client Protobuff Issue

[Riak Java Client 2.0.3] and [Protobuff Version 3.0.0-beta-1]

Getting a conversion error when I try to store a protobuf object in Riak. 

Location videoObjectLocation = new Location(videoBucket, video.getId());
StoreValue storeOp = new StoreValue.Builder(Base64.getEncoder().encode(video.toByteArray()))
    .withLocation(videoObjectLocation)
    .build();
StoreValue storeOp = new StoreValue.Builder(video)
    .withLocation(videoObjectLocation)
    .build();
// This line throws ConversionException
StoreValue.Response storeOpResp = client.execute(storeOp);

I am using protobuf 3. Is that supported? Or am I supposed to be storing the value in a different way?

Full stack trace.
com.basho.riak.client.api.convert.ConversionException: com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: com.appz.video.backend.Video["unknownFields"]->com.google.protobuf.UnknownFieldSet["defaultInstanceForType"])
    at com.basho.riak.client.api.convert.JSONConverter.fromDomain(JSONConverter.java:122)
    at com.basho.riak.client.api.convert.Converter.fromDomain(Converter.java:153)
    at com.basho.riak.client.api.commands.kv.StoreValue.executeAsync(StoreValue.java:108)
    at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:87)
    at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:328)
    at com.appz.video.scraper.dao.impl.riak.VideoDaoRiakImpl.storeVideo2(VideoDaoRiakImpl.java:137)
    at com.appz.video.scraper.dao.impl.riak.VideoDaoRiakImplLiveTest.createVideo2_ShouldReturnTrue(VideoDaoRiakImplLiveTest.java:221)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: com.appz.video.backend.Video["unknownFields"]->com.google.protobuf.UnknownFieldSet["defaultInstanceForType"])
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:781)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:569)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3383)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2801)
    at com.basho.riak.client.api.convert.JSONConverter.fromDomain(JSONConverter.java:117)
    ... 32 more

**Comment by alexmoore** [comment]
Hi Vchan,

I think you're just using the library a little incorrectly.  The Java client uses protocol buffers 2.5 for the network encoding, but the library is shaded so you shouldn't have any issues with protobuf 3 elsewhere in your application.

The Java client's StoreValue class will try to convert whatever object you pass in to JSON by default, which is the error you're seeing here.  If you'd like to make a custom converter to store it as a protocol buffers encoded binary string, you need to implement a [Converter](http://basho.github.io/riak-java-client/2.0.1/com/basho/riak/client/api/convert/Converter.html), and then register it with the [ConverterFactory](http://basho.github.io/riak-java-client/2.0.0/com/basho/riak/client/api/convert/ConverterFactory.html) class.

Once you have the Converter implemented and registered in your code, you should just have to pass in the whole unserialized object into the StoreValue builder, and your converter code will serialize / deserialize it for you.  

```
class VideoConverter implements Converter<Video> { ... }

ConverterFactory.getInstance().registerConverterForClass(Video.class, new VideoConverter());
...
StoreValue storeOp = new StoreValue.Builder(video)
.withLocation(videoObjectLocation)
.build();

```

Thanks,
Alex
